"""add user avatar

Revision ID: 6d6ecfe67bcc
Revises: 8656f79d7a02
Create Date: 2019-04-03 14:39:00.140649

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d6ecfe67bcc'
down_revision = '8656f79d7a02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'from_post_author',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('comment', 'is_hidden',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('post', 'can_comment',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('task', 'complete',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.add_column('user', sa.Column('avatar_l', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('avatar_m', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('avatar_raw', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('avatar_s', sa.String(length=64), nullable=True))
    op.alter_column('user', 'confirmed',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'confirmed',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('user', 'avatar_s')
    op.drop_column('user', 'avatar_raw')
    op.drop_column('user', 'avatar_m')
    op.drop_column('user', 'avatar_l')
    op.alter_column('task', 'complete',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('post', 'can_comment',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('comment', 'is_hidden',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('comment', 'from_post_author',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    # ### end Alembic commands ###
