"""add language to posts

Revision ID: 71908638c03b
Revises: 02d8be639c9f
Create Date: 2019-03-18 13:09:39.457171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71908638c03b'
down_revision = '02d8be639c9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
