"""add post title

Revision ID: cf1cc05c063c
Revises: 4cd1a1a6f1da
Create Date: 2019-03-26 07:53:12.250875

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cf1cc05c063c'
down_revision = '4cd1a1a6f1da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('title', sa.String(length=60), nullable=True))
    op.drop_column('post', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body', mysql.VARCHAR(collation='utf8_bin', length=140), nullable=True))
    op.drop_column('post', 'title')
    # ### end Alembic commands ###
